name: Build, Test, Lint

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      test_var: "Dummy"

jobs:
  python-ci-pipeline:
    uses: MartinHeinz/workflows/blob/master/.github/workflows/python.yaml